<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Objectives" data-toc-modified-id="Objectives-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Objectives</a></span></li><li><span><a href="#Motivation" data-toc-modified-id="Motivation-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Motivation</a></span></li><li><span><a href="#Relational-Databases" data-toc-modified-id="Relational-Databases-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Relational Databases</a></span><ul class="toc-item"><li><span><a href="#Database-Schema" data-toc-modified-id="Database-Schema-3.1"><span class="toc-item-num">3.1&nbsp;&nbsp;</span>Database Schema</a></span></li><li><span><a href="#Columns" data-toc-modified-id="Columns-3.2"><span class="toc-item-num">3.2&nbsp;&nbsp;</span>Columns</a></span></li><li><span><a href="#Keys" data-toc-modified-id="Keys-3.3"><span class="toc-item-num">3.3&nbsp;&nbsp;</span>Keys</a></span></li></ul></li><li><span><a href="#SQLite" data-toc-modified-id="SQLite-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>SQLite</a></span><ul class="toc-item"><li><span><a href="#Sidebar:-More-About-SQLite" data-toc-modified-id="Sidebar:-More-About-SQLite-4.1"><span class="toc-item-num">4.1&nbsp;&nbsp;</span><em>Sidebar: More About SQLite</em></a></span></li><li><span><a href="#Load-a-SQLite-DB" data-toc-modified-id="Load-a-SQLite-DB-4.2"><span class="toc-item-num">4.2&nbsp;&nbsp;</span>Load a SQLite DB</a></span></li><li><span><a href="#Query-the-airports-Table" data-toc-modified-id="Query-the-airports-Table-4.3"><span class="toc-item-num">4.3&nbsp;&nbsp;</span>Query the <code>airports</code> Table</a></span></li><li><span><a href="#pd.read_sql()" data-toc-modified-id="pd.read_sql()-4.4"><span class="toc-item-num">4.4&nbsp;&nbsp;</span><code>pd.read_sql()</code></a></span></li><li><span><a href="#Explore-the-Schema" data-toc-modified-id="Explore-the-Schema-4.5"><span class="toc-item-num">4.5&nbsp;&nbsp;</span>Explore the Schema</a></span></li><li><span><a href="#Exercise" data-toc-modified-id="Exercise-4.6"><span class="toc-item-num">4.6&nbsp;&nbsp;</span>Exercise</a></span></li></ul></li><li><span><a href="#Writing-SQL-Queries" data-toc-modified-id="Writing-SQL-Queries-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Writing SQL Queries</a></span><ul class="toc-item"><li><span><a href="#SELECT-Statement" data-toc-modified-id="SELECT-Statement-5.1"><span class="toc-item-num">5.1&nbsp;&nbsp;</span>SELECT Statement</a></span></li><li><span><a href="#SELECT:-Picking-Columns" data-toc-modified-id="SELECT:-Picking-Columns-5.2"><span class="toc-item-num">5.2&nbsp;&nbsp;</span>SELECT: Picking Columns</a></span><ul class="toc-item"><li><span><a href="#DISTINCT" data-toc-modified-id="DISTINCT-5.2.1"><span class="toc-item-num">5.2.1&nbsp;&nbsp;</span><code>DISTINCT</code></a></span></li><li><span><a href="#AS" data-toc-modified-id="AS-5.2.2"><span class="toc-item-num">5.2.2&nbsp;&nbsp;</span><code>AS</code></a></span></li><li><span><a href="#Functions" data-toc-modified-id="Functions-5.2.3"><span class="toc-item-num">5.2.3&nbsp;&nbsp;</span>Functions</a></span><ul class="toc-item"><li><span><a href="#Aggregation" data-toc-modified-id="Aggregation-5.2.3.1"><span class="toc-item-num">5.2.3.1&nbsp;&nbsp;</span>Aggregation</a></span></li><li><span><a href="#Datatype-Compatibility" data-toc-modified-id="Datatype-Compatibility-5.2.3.2"><span class="toc-item-num">5.2.3.2&nbsp;&nbsp;</span>Datatype Compatibility</a></span></li><li><span><a href="#CAST()" data-toc-modified-id="CAST()-5.2.3.3"><span class="toc-item-num">5.2.3.3&nbsp;&nbsp;</span><code>CAST()</code></a></span></li></ul></li><li><span><a href="#Exercise" data-toc-modified-id="Exercise-5.2.4"><span class="toc-item-num">5.2.4&nbsp;&nbsp;</span>Exercise</a></span></li></ul></li><li><span><a href="#FROM:-Picking-Tables" data-toc-modified-id="FROM:-Picking-Tables-5.3"><span class="toc-item-num">5.3&nbsp;&nbsp;</span>FROM: Picking Tables</a></span></li><li><span><a href="#WHERE:-Picking-Rows" data-toc-modified-id="WHERE:-Picking-Rows-5.4"><span class="toc-item-num">5.4&nbsp;&nbsp;</span>WHERE: Picking Rows</a></span><ul class="toc-item"><li><span><a href="#IS" data-toc-modified-id="IS-5.4.1"><span class="toc-item-num">5.4.1&nbsp;&nbsp;</span><code>IS</code></a></span></li></ul></li><li><span><a href="#ORDER-BY:-Sorting-Results" data-toc-modified-id="ORDER-BY:-Sorting-Results-5.5"><span class="toc-item-num">5.5&nbsp;&nbsp;</span>ORDER BY: Sorting Results</a></span></li><li><span><a href="#LIMIT:-Number-of-Results" data-toc-modified-id="LIMIT:-Number-of-Results-5.6"><span class="toc-item-num">5.6&nbsp;&nbsp;</span>LIMIT: Number of Results</a></span></li></ul></li><li><span><a href="#Exercises" data-toc-modified-id="Exercises-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>Exercises</a></span><ul class="toc-item"><li><span><a href="#Country-List" data-toc-modified-id="Country-List-6.1"><span class="toc-item-num">6.1&nbsp;&nbsp;</span>Country List</a></span></li><li><span><a href="#Southern-Airports" data-toc-modified-id="Southern-Airports-6.2"><span class="toc-item-num">6.2&nbsp;&nbsp;</span>Southern Airports</a></span></li><li><span><a href="#Active-UK-Airlines" data-toc-modified-id="Active-UK-Airlines-6.3"><span class="toc-item-num">6.3&nbsp;&nbsp;</span>Active UK Airlines</a></span></li><li><span><a href="#Explore-Routes" data-toc-modified-id="Explore-Routes-6.4"><span class="toc-item-num">6.4&nbsp;&nbsp;</span>Explore Routes</a></span></li></ul></li><li><span><a href="#Level-Up:-CASE" data-toc-modified-id="Level-Up:-CASE-7"><span class="toc-item-num">7&nbsp;&nbsp;</span>Level Up: <code>CASE</code></a></span></li><li><span><a href="#Level-Up:-SQL-Joins" data-toc-modified-id="Level-Up:-SQL-Joins-8"><span class="toc-item-num">8&nbsp;&nbsp;</span>Level Up: SQL Joins</a></span></li></ul></div>

![sql](images/sql-logo.jpg)

# Objectives

- Describe relational databases
- Connect to a SQLite database and get schema information
- Use SQL SELECT and `pd.read_sql()` to query databases 
- Use WHERE, ORDER BY, and LIMIT to modify queries

# Motivation

Most data aren't stored in static files like CSVs or JSONs. Rather, data are typically stored in **databases** that make it easy for many users to store, update, share, and access data in real time. CSVs and JSONs are just extracts of some data from those databases.

**Structured Query Language (SQL)** is a common language for interacting with databases, and will be invaluable for you in almost any data role. You will use it often to get the data that you need for your analyses.

# Relational Databases

**Relational databases** typically have multiple **tables** containing data, and the tables have defined relationships.

![rdb](images/relational-dbms-model.png)
[reference for image ](https://www.studytonight.com/dbms/database-model.php)

## Database Schema

Each database has a **schema** that defines the structure of the database, including the tables and relationships between tables.

![schema](images/MySQL_Schema_Music_Example.png)

[source of image](https://database.guide/what-is-a-database-schema/)

##  Columns

Similar to how DataFrames can have multiple Series, tables can have multiple **columns** (aka "fields"). Each column has a datatype, but the datatypes available for SQL table columns differ from the datatypes in `pandas`.

![table example](images/columns.png)

## Keys

A **primary key** uniquely identifies each row in a table. This is often a unique ID number.
A **foreign key** is used in one table to refer to the primary key from another table.

We **join** tables using these keys to get data from multiple tables at once - we will cover this in a future lesson on SQL Joins.

![rdb](images/relational-dbms-model.png)
[reference for image ](https://www.studytonight.com/dbms/database-model.php)

# SQLite

![sqlite](images/SQLite-Python.jpg)

SQLite is one of many tools that exist to create databases. We use it here because it is easy to integrate into a Jupyter Notebook using the `sqlite3` package. 

There are many other database tools out there, and they all work somewhat differently with their own SQL dialects. Just know that the specific methods or syntax you see here will differ slightly in other database implementations.

## _Sidebar: More About SQLite_

"SQLite is a C library that provides a lightweight disk-based database that doesn’t require a separate server process and allows accessing the database using a nonstandard variant of the SQL query language. Some applications can use SQLite for internal data storage. It’s also possible to prototype an application using SQLite and then port the code to a larger database such as PostgreSQL or Oracle." - [sqlite documentation](https://docs.python.org/2/library/sqlite3.html)

## Load a SQLite DB

Import the `sqlite3` package, which will allow us to load a SQLite database.

In [1]:
import sqlite3

In this repository is a `flights.db` file that we can open as a SQLite database. This database contains tables with information about airlines, airports, and flight routes.

In [2]:
!ls

08-pandas_dataframes.ipynb data
13-sql_queries.ipynb       images
completed

First, we'll use the `sqlite3` package to create a connection to the database, which is currently just stored in that file on our hard drive.

In [3]:
con = sqlite3.connect('data/flights.db')

In [4]:
type(con)

sqlite3.Connection

Next, we'll create a cursor to interact with the database. Like the cursor for your mouse interacts with pixels on your screen, this cursor will allow us to interact with the elements of the database.

In [6]:
cursor = con.cursor()

In [7]:
type(cursor)

sqlite3.Cursor

## Query the `airports` Table

We will write a simple query using the SQL SELECT statement, which returns data from the database. We write the query as a string, which will then get parsed via the `sqlite3` package.

In this case, we say `SELECT *` to specify that we want data from all columns, and we say `FROM airports` to specify that we want data from the `airports` table.

In [8]:
airports_query = """
SELECT *
FROM airports;
"""

To run this query, we use the `.execute()` method with our cursor.

In [9]:
cursor.execute(airports_query)

Note that the `.execute()` method didn't actually return our data. The data is now just available in our cursor object. We'll use the `.fetchall()` method to get all the rows from our query.

In [10]:
cursor.fetchall()

[(0,
  '1',
  'Goroka',
  'Goroka',
  'Papua New Guinea',
  'GKA',
  'AYGA',
  '-6.081689',
  '145.391881',
  '5282',
  '10',
  'U',
  'Pacific/Port_Moresby'),
 (1,
  '2',
  'Madang',
  'Madang',
  'Papua New Guinea',
  'MAG',
  'AYMD',
  '-5.207083',
  '145.7887',
  '20',
  '10',
  'U',
  'Pacific/Port_Moresby'),
 (2,
  '3',
  'Mount Hagen',
  'Mount Hagen',
  'Papua New Guinea',
  'HGU',
  'AYMH',
  '-5.826789',
  '144.295861',
  '5388',
  '10',
  'U',
  'Pacific/Port_Moresby'),
 (3,
  '4',
  'Nadzab',
  'Nadzab',
  'Papua New Guinea',
  'LAE',
  'AYNZ',
  '-6.569828',
  '146.726242',
  '239',
  '10',
  'U',
  'Pacific/Port_Moresby'),
 (4,
  '5',
  'Port Moresby Jacksons Intl',
  'Port Moresby',
  'Papua New Guinea',
  'POM',
  'AYPY',
  '-9.443383',
  '147.22005',
  '146',
  '10',
  'U',
  'Pacific/Port_Moresby'),
 (5,
  '6',
  'Wewak Intl',
  'Wewak',
  'Papua New Guinea',
  'WWK',
  'AYWK',
  '-3.583828',
  '143.669186',
  '19',
  '10',
  'U',
  'Pacific/Port_Moresby'),
 (6,
  '7',
  'Narsarsuaq',
  'Narssarssuaq',
  'Greenland',
  'UAK',
  'BGBW',
  '61.160517',
  '-45.425978',
  '112',
  '-3',
  'E',
  'America/Godthab'),
 (7,
  '8',
  'Nuuk',
  'Godthaab',
  'Greenland',
  'GOH',
  'BGGH',
  '64.190922',
  '-51.678064',
  '283',
  '-3',
  'E',
  'America/Godthab'),
 (8,
  '9',
  'Sondre Stromfjord',
  'Sondrestrom',
  'Greenland',
  'SFJ',
  'BGSF',
  '67.016969',
  '-50.689325',
  '165',
  '-3',
  'E',
  'America/Godthab'),
 (9,
  '10',
  'Thule Air Base',
  'Thule',
  'Greenland',
  'THU',
  'BGTL',
  '76.531203',
  '-68.703161',
  '251',
  '-4',
  'E',
  'America/Thule'),
 (10,
  '11',
  'Akureyri',
  'Akureyri',
  'Iceland',
  'AEY',
  'BIAR',
  '65.659994',
  '-18.072703',
  '6',
  '0',
  'N',
  'Atlantic/Reykjavik'),
 (11,
  '12',
  'Egilsstadir',
  'Egilsstadir',
  'Iceland',
  'EGS',
  'BIEG',
  '65.283333',
  '-14.401389',
  '76',
  '0',
  'N',
  'Atlantic/Reykjavik'),
 (12,
  '13',
  'Hornafjordur',
  'Hofn',
  'Iceland',
  'HFN',
  'BIHN',
  '64.295556',
  '-15.227222',
  '24',
  '0',
  'N',
  'Atlantic/Reykjavik'),
 (13,
  '14',
  'Husavik',
  'Husavik',
  'Iceland',
  'HZK',
  'BIHU',
  '65.952328',
  '-17.425978',
  '48',
  '0',
  'N',
  'Atlantic/Reykjavik'),
 (14,
  '15',
  'Isafjordur',
  'Isafjordur',
  'Iceland',
  'IFJ',
  'BIIS',
  '66.058056',
  '-23.135278',
  '8',
  '0',
  'N',
  'Atlantic/Reykjavik'),
 (15,
  '16',
  'Keflavik International Airport',
  'Keflavik',
  'Iceland',
  'KEF',
  'BIKF',
  '63.985',
  '-22.605556',
  '171',
  '0',
  'N',
  'Atlantic/Reykjavik'),
 (16,
  '17',
  'Patreksfjordur',
  'Patreksfjordur',
  'Iceland',
  'PFJ',
  'BIPA',
  '65.555833',
  '-23.965',
  '11',
  '0',
  'N',
  'Atlantic/Reykjavik'),
 (17,
  '18',
  'Reykjavik',
  'Reykjavik',
  'Iceland',
  'RKV',
  'BIRK',
  '64.13',
  '-21.940556',
  '48',
  '0',
  'N',
  'Atlantic/Reykjavik'),
 (18,
  '19',
  'Siglufjordur',
  'Siglufjordur',
  'Iceland',
  'SIJ',
  'BISI',
  '66.133333',
  '-18.916667',
  '10',
  '0',
  'N',
  'Atlantic/Reykjavik'),
 (19,
  '20',
  'Vestmannaeyjar',
  'Vestmannaeyjar',
  'Iceland',
  'VEY',
  'BIVM',
  '63.424303',
  '-20.278875',
  '326',
  '0',
  'N',
  'Atlantic/Reykjavik'),
 (20,
  '21',
  'Sault Ste Marie',
  'Sault Sainte Marie',
  'Canada',
  'YAM',
  'CYAM',
  '46.485001',
  '-84.509445',
  '630',
  '-5',
  'A',
  'America/Toronto'),
 (21,
  '22',
  'Winnipeg St Andrews',
  'Winnipeg',
  'Canada',
  'YAV',
  'CYAV',
  '50.056389',
  '-97.0325',
  '760',
  '-6',
  'A',
  'America/Winnipeg'),
 (22,
  '23',
  'Shearwater',
  'Halifax',
  'Canada',
  'YAW',
  'CYAW',
  '44.639721',
  '-63.499444',
  '167',
  '-4',
  'A',
  'America/Halifax'),
 (23,
  '24',
  'St Anthony',
  'St. Anthony',
  'Canada',
  'YAY',
  'CYAY',
  '51.391944',
  '-56.083056',
  '108',
  '-3.5',
  'A',
  'America/St_Johns'),
 (24,
  '25',
  'Tofino',
  'Tofino',
  'Canada',
  'YAZ',
  'CYAZ',
  '49.082222',
  '-125.7725',
  '80',
  '-8',
  'A',
  'America/Vancouver'),
 (25,
  '26',
  'Kugaaruk',
  'Pelly Bay',
  'Canada',
  'YBB',
  'CYBB',
  '68.534444',
  '-89.808056',
  '56',
  '-7',
  'A',
  'America/Edmonton'),
 (26,
  '27',
  'Baie Comeau',
  'Baie Comeau',
  'Canada',
  'YBC',
  'CYBC',
  '49.1325',
  '-68.204444',
  '71',
  '-5',
  'A',
  'America/Toronto'),
 (27,
  '28',
  'Bagotville',
  'Bagotville',
  'Canada',
  'YBG',
  'CYBG',
  '48.330555',
  '-70.996391',
  '522',
  '-5',
  'A',
  'America/Toronto'),
 (28,
  '29',
  'Baker Lake',
  'Baker Lake',
  'Canada',
  'YBK',
  'CYBK',
  '64.298889',
  '-96.077778',
  '59',
  '-6',
  'A',
  'America/Winnipeg'),
 (29,
  '30',
  'Campbell River',
  'Campbell River',
  'Canada',
  'YBL',
  'CYBL',
  '49.950832',
  '-125.270833',
  '346',
  '-8',
  'A',
  'America/Vancouver'),
 (30,
  '31',
  'Brandon Muni',
  'Brandon',
  'Canada',
  'YBR',
  'CYBR',
  '49.91',
  '-99.951944',
  '1343',
  '-6',
  'A',
  'America/Winnipeg'),
 (31,
  '32',
  'Cambridge Bay',
  'Cambridge Bay',
  'Canada',
  'YCB',
  'CYCB',
  '69.108055',
  '-105.138333',
  '90',
  '-7',
  'A',
  'America/Edmonton'),
 (32,
  '33',
  'Nanaimo',
  'Nanaimo',
  'Canada',
  'YCD',
  'CYCD',
  '49.052333',
  '-123.870167',
  '93',
  '-8',
  'A',
  'America/Vancouver'),
 (33,
  '34',
  'Castlegar',
  'Castlegar',
  'Canada',
  'YCG',
  'CYCG',
  '49.296389',
  '-117.6325',
  '1624',
  '-8',
  'A',
  'America/Vancouver'),
 (34,
  '35',
  'Miramichi',
  'Chatham',
  'Canada',
  'YCH',
  'CYCH',
  '47.007778',
  '-65.449167',
  '108',
  '-4',
  'A',
  'America/Halifax'),
 (35,
  '36',
  'Charlo',
  'Charlo',
  'Canada',
  'YCL',
  'CYCL',
  '47.990833',
  '-66.330278',
  '132',
  '-4',
  'A',
  'America/Halifax'),
 (36,
  '37',
  'Kugluktuk',
  'Coppermine',
  'Canada',
  'YCO',
  'CYCO',
  '67.816667',
  '-115.143889',
  '74',
  '-7',
  'A',
  'America/Edmonton'),
 (37,
  '38',
  'Coronation',
  'Coronation',
  'Canada',
  'YCT',
  'CYCT',
  '52.075001',
  '-111.445278',
  '2595',
  '-7',
  'A',
  'America/Edmonton'),
 (38,
  '39',
  'Chilliwack',
  'Chilliwack',
  'Canada',
  'YCW',
  'CYCW',
  '49.152779',
  '-121.93889',
  '32',
  '-8',
  'A',
  'America/Vancouver'),
 (39,
  '40',
  'Clyde River',
  'Clyde River',
  'Canada',
  'YCY',
  'CYCY',
  '70.486111',
  '-68.516667',
  '87',
  '-5',
  'A',
  'America/Toronto'),
 (40,
  '41',
  'Fairmont Hot Springs',
  'Coral Harbour',
  'Canada',
  'YZS',
  'CYCZ',
  '64.193333',
  '-83.359444',
  '2661',
  '-5',
  'A',
  'America/Coral_Harbour'),
 (41,
  '42',
  'Dawson City',
  'Dawson',
  'Canada',
  'YDA',
  'CYDA',
  '64.043056',
  '-139.127778',
  '1215',
  '-8',
  'A',
  'America/Vancouver'),
 (42,
  '43',
  'Burwash',
  'Burwash',
  'Canada',
  'YDB',
  'CYDB',
  '61.371111',
  '-139.040556',
  '2647',
  '-8',
  'A',
  'America/Vancouver'),
 (43,
  '44',
  'Princeton',
  'Princeton',
  'Canada',
  'YDC',
  'CYDC',
  '49.468056',
  '-120.511389',
  '2298',
  '-8',
  'A',
  'America/Vancouver'),
 (44,
  '45',
  'Deer Lake',
  'Deer Lake',
  'Canada',
  'YDF',
  'CYDF',
  '49.210833',
  '-57.391388',
  '72',
  '-3.5',
  'A',
  'America/St_Johns'),
 (45,
  '46',
  'Dease Lake',
  'Dease Lake',
  'Canada',
  'YDL',
  'CYDL',
  '58.422222',
  '-130.032222',
  '2600',
  '-8',
  'A',
  'America/Vancouver'),
 (46,
  '47',
  'Dauphin Barker',
  'Dauphin',
  'Canada',
  'YDN',
  'CYDN',
  '51.100834',
  '-100.0525',
  '999',
  '-6',
  'A',
  'America/Winnipeg'),
 (47,
  '48',
  'Dawson Creek',
  'Dawson Creek',
  'Canada',
  'YDQ',
  'CYDQ',
  '55.742333',
  '-120.183',
  '2148',
  '-7',
  'A',
  'America/Dawson_Creek'),
 (48,
  '49',
  'Edmonton Intl',
  'Edmonton',
  'Canada',
  'YEG',
  'CYEG',
  '53.309723',
  '-113.579722',
  '2373',
  '-7',
  'A',
  'America/Edmonton'),
 (49,
  '50',
  'Arviat',
  'Eskimo Point',
  'Canada',
  'YEK',
  'CYEK',
  '61.094166',
  '-94.070833',
  '32',
  '-6',
  'A',
  'America/Winnipeg'),
 (50,
  '51',
  'Estevan',
  'Estevan',
  'Canada',
  'YEN',
  'CYEN',
  '49.210278',
  '-102.965833',
  '1905',
  '-6',
  'N',
  'America/Regina'),
 (51,
  '52',
  'Edson',
  'Edson',
  'Canada',
  'YET',
  'CYET',
  '53.578888',
  '-116.465',
  '3041',
  '-7',
  'A',
  'America/Edmonton'),
 (52,
  '53',
  'Eureka',
  'Eureka',
  'Canada',
  'YEU',
  'CYEU',
  '79.994722',
  '-85.814167',
  '256',
  '-6',
  'A',
  'America/Winnipeg'),
 (53,
  '54',
  'Inuvik Mike Zubko',
  'Inuvik',
  'Canada',
  'YEV',
  'CYEV',
  '68.304167',
  '-133.482778',
  '224',
  '-7',
  'A',
  'America/Edmonton'),
 (54,
  '55',
  'Iqaluit',
  'Iqaluit',
  'Canada',
  'YFB',
  'CYFB',
  '63.75639',
  '-68.555832',
  '110',
  '-5',
  'A',
  'America/Toronto'),
 (55,
  '56',
  'Fredericton',
  'Fredericton',
  'Canada',
  'YFC',
  'CYFC',
  '45.868889',
  '-66.537222',
  '68',
  '-4',
  'A',
  'America/Halifax'),
 (56,
  '57',
  'Forestville',
  'Forestville',
  'Canada',
  None,
  'CYFE',
  '48.746111',
  '-69.097222',
  '293',
  '-5',
  'A',
  'America/Toronto'),
 (57,
  '58',
  'Flin Flon',
  'Flin Flon',
  'Canada',
  'YFO',
  'CYFO',
  '54.678055',
  '-101.681667',
  '997',
  '-6',
  'A',
  'America/Winnipeg'),
 (58,
  '59',
  'Fort Resolution',
  'Fort Resolution',
  'Canada',
  'YFR',
  'CYFR',
  '61.180832',
  '-113.689722',
  '526',
  '-7',
  'A',
  'America/Edmonton'),
 (59,
  '60',
  'Fort Simpson',
  'Fort Simpson',
  'Canada',
  'YFS',
  'CYFS',
  '61.760153',
  '-121.236525',
  '555',
  '-7',
  'A',
  'America/Edmonton'),
 (60,
  '61',
  'Kingston',
  'Kingston',
  'Canada',
  'YGK',
  'CYGK',
  '44.225277',
  '-76.596944',
  '305',
  '-5',
  'A',
  'America/Toronto'),
 (61,
  '62',
  'La Grande Riviere',
  'La Grande Riviere',
  'Canada',
  'YGL',
  'CYGL',
  '53.625278',
  '-77.704167',
  '639',
  '-5',
  'A',
  'America/Toronto'),
 (62,
  '63',
  'Gaspe',
  'Gaspe',
  'Canada',
  'YGP',
  'CYGP',
  '48.775278',
  '-64.478611',
  '108',
  '-5',
  'A',
  'America/Toronto'),
 (63,
  '64',
  'Geraldton Greenstone Regional',
  'Geraldton',
  'Canada',
  'YGQ',
  'CYGQ',
  '49.778332',
  '-86.939445',
  '1144',
  '-5',
  'A',
  'America/Toronto'),
 (64,
  '65',
  'Iles De La Madeleine',
  'Iles De La Madeleine',
  'Canada',
  'YGR',
  'CYGR',
  '47.424721',
  '-61.778056',
  '35',
  '-5',
  'A',
  'America/Toronto'),
 (65,
  '66',
  'Hudson Bay',
  'Hudson Bay',
  'Canada',
  'YHB',
  'CYHB',
  '52.816666',
  '-102.31139',
  '1175',
  '-6',
  'N',
  'America/Regina'),
 (66,
  '67',
  'Dryden Rgnl',
  'Dryden',
  'Canada',
  'YHD',
  'CYHD',
  '49.831667',
  '-92.744167',
  '1354',
  '-6',
  'A',
  'America/Winnipeg'),
 (67,
  '68',
  'Ulukhaktok Holman',
  'Holman Island',
  'Canada',
  'YHI',
  'CYHI',
  '70.762778',
  '-117.806111',
  '117',
  '-7',
  'A',
  'America/Edmonton'),
 (68,
  '69',
  'Gjoa Haven',
  'Gjoa Haven',
  'Canada',
  'YHK',
  'CYHK',
  '68.635556',
  '-95.849722',
  '152',
  '-7',
  'A',
  'America/Edmonton'),
 (69,
  '70',
  'Hamilton',
  'Hamilton',
  'Canada',
  'YHM',
  'CYHM',
  '43.173611',
  '-79.935',
  '780',
  '-5',
  'A',
  'America/Toronto'),
 (70,
  '71',
  'St Hubert',
  'Montreal',
  'Canada',
  'YHU',
  'CYHU',
  '45.5175',
  '-73.416944',
  '90',
  '-5',
  'A',
  'America/Toronto'),
 (71,
  '72',
  'Hay River',
  'Hay River',
  'Canada',
  'YHY',
  'CYHY',
  '60.839722',
  '-115.782778',
  '543',
  '-7',
  'A',
  'America/Edmonton'),
 (72,
  '73',
  'Halifax Intl',
  'Halifax',
  'Canada',
  'YHZ',
  'CYHZ',
  '44.880833',
  '-63.50861',
  '477',
  '-4',
  'A',
  'America/Halifax'),
 (73,
  '74',
  'Atikokan Muni',
  'Atikokan',
  'Canada',
  'YIB',
  'CYIB',
  '48.773888',
  '-91.638611',
  '1408',
  '-5',
  'A',
  'America/Coral_Harbour'),
 (74,
  '75',
  'Pond Inlet',
  'Pond Inlet',
  'Canada',
  'YIO',
  'CYIO',
  '72.683334',
  '-77.966667',
  '181',
  '-5',
  'A',
  'America/Toronto'),
 (75,
  '76',
  'St Jean',
  'St. Jean',
  'Canada',
  'YJN',
  'CYJN',
  '45.294445',
  '-73.281111',
  '136',
  '-5',
  'A',
  'America/Toronto'),
 (76,
  '77',
  'Stephenville',
  'Stephenville',
  'Canada',
  'YJT',
  'CYJT',
  '48.544167',
  '-58.549999',
  '80',
  '-3.5',
  'A',
  'America/St_Johns'),
 (77,
  '78',
  'Kamloops',
  'Kamloops',
  'Canada',
  'YKA',
  'CYKA',
  '50.702222',
  '-120.444444',
  '1133',
  '-8',
  'A',
  'America/Vancouver'),
 (78,
  '79',
  'Waterloo',
  'Waterloo',
  'Canada',
  'YKF',
  'CYKF',
  '43.460833',
  '-80.378611',
  '1054',
  '-5',
  'A',
  'America/Toronto'),
 (79,
  '80',
  'Schefferville',
  'Schefferville',
  'Canada',
  'YKL',
  'CYKL',
  '54.805278',
  '-66.805278',
  '1709',
  '-5',
  'A',
  'America/Toronto'),
 (80,
  '81',
  'Kindersley',
  'Kindersley',
  'Canada',
  'YKY',
  'CYKY',
  '51.5175',
  '-109.180833',
  '2277',
  '-6',
  'N',
  'America/Regina'),
 (81,
  '82',
  'Buttonville Muni',
  'Toronto',
  'Canada',
  'YKZ',
  'CYKZ',
  '43.862221',
  '-79.37',
  '650',
  '-5',
  'A',
  'America/Toronto'),
 (82,
  '83',
  'Chapleau',
  'Chapleau',
  'Canada',
  'YLD',
  'CYLD',
  '47.82',
  '-83.346667',
  '1470',
  '-5',
  'A',
  'America/Toronto'),
 (83,
  '84',
  'Meadow Lake',
  'Meadow Lake',
  'Canada',
  'YLJ',
  'CYLJ',
  '54.125278',
  '-108.522778',
  '1576',
  '-6',
  'N',
  'America/Regina'),
 (84,
  '85',
  'Lloydminster',
  'Lloydminster',
  'Canada',
  'YLL',
  'CYLL',
  '53.309166',
  '-110.0725',
  '2193',
  '-7',
  'A',
  'America/Edmonton'),
 (85,
  '86',
  'Alert',
  'Alert',
  'Canada',
  'YLT',
  'CYLT',
  '82.517778',
  '-62.280556',
  '100',
  '-5',
  'A',
  'America/Toronto'),
 (86,
  '87',
  'Kelowna',
  'Kelowna',
  'Canada',
  'YLW',
  'CYLW',
  '49.956112',
  '-119.377778',
  '1409',
  '-8',
  'A',
  'America/Vancouver'),
 (87,
  '88',
  'Mayo',
  'Mayo',
  'Canada',
  'YMA',
  'CYMA',
  '63.616389',
  '-135.868333',
  '1653',
  '-8',
  'A',
  'America/Vancouver'),
 (88,
  '89',
  'Moose Jaw Air Vice Marshal C M Mcewen',
  'Moose Jaw',
  'Canada',
  'YMJ',
  'CYMJ',
  '50.330278',
  '-105.559167',
  '1892',
  '-6',
  'N',
  'America/Regina'),
 (89,
  '90',
  'Fort Mcmurray',
  'Fort Mcmurray',
  'Canada',
  'YMM',
  'CYMM',
  '56.653333',
  '-111.221944',
  '1211',
  '-7',
  'A',
  'America/Edmonton'),
 (90,
  '91',
  'Moosonee',
  'Moosonee',
  'Canada',
  'YMO',
  'CYMO',
  '51.291111',
  '-80.607778',
  '30',
  '-5',
  'A',
  'America/Toronto'),
 (91,
  '92',
  'Maniwaki',
  'Maniwaki',
  'Canada',
  'YMW',
  'CYMW',
  '46.272778',
  '-75.990556',
  '656',
  '-5',
  'A',
  'America/Toronto'),
 (92,
  '93',
  'Montreal Intl Mirabel',
  'Montreal',
  'Canada',
  'YMX',
  'CYMX',
  '45.681944',
  '-74.005278',
  '270',
  '-5',
  'A',
  'America/Toronto'),
 (93,
  '94',
  'Natashquan',
  'Natashquan',
  'Canada',
  'YNA',
  'CYNA',
  '50.19',
  '-61.789167',
  '39',
  '-5',
  'A',
  'America/Toronto'),
 (94,
  '95',
  'Gatineau',
  'Gatineau',
  'Canada',
  'YND',
  'CYND',
  '45.521694',
  '-75.563589',
  '211',
  '-5',
  'A',
  'America/Toronto'),
 (95,
  '96',
  'Matagami',
  'Matagami',
  'Canada',
  'YNM',
  'CYNM',
  '49.761667',
  '-77.802778',
  '918',
  '-5',
  'A',
  'America/Toronto'),
 (96,
  '97',
  'Old Crow',
  'Old Crow',
  'Canada',
  'YOC',
  'CYOC',
  '67.570556',
  '-139.839167',
  '824',
  '-8',
  'A',
  'America/Vancouver'),
 (97,
  '98',
  'Cold Lake',
  'Cold Lake',
  'Canada',
  'YOD',
  'CYOD',
  '54.404999',
  '-110.279444',
  '1775',
  '-7',
  'A',
  'America/Edmonton'),
 (98,
  '99',
  'High Level',
  'High Level',
  'Canada',
  'YOJ',
  'CYOJ',
  '58.621389',
  '-117.164722',
  '1110',
  '-7',
  'A',
  'America/Edmonton'),
 (99,
  '100',
  'Ottawa Macdonald Cartier Intl',
  'Ottawa',
  'Canada',
  'YOW',
  'CYOW',
  '45.3225',
  '-75.669167',
  '374',
  '-5',
  'A',
  'America/Toronto'),
 (100,
  '101',
  'Prince Albert Glass Field',
  'Prince Albert',
  'Canada',
  'YPA',
  'CYPA',
  '53.214167',
  '-105.672778',
  '1405',
  '-6',
  'N',
  'America/Regina'),
 (101,
  '102',
  'Peace River',
  'Peace River',
  'Canada',
  'YPE',
  'CYPE',
  '56.226944',
  '-117.447222',
  '1873',
  '-7',
  'A',
  'America/Edmonton'),
 (102,
  '103',
  'Southport',
  'Portage-la-prairie',
  'Canada',
  'YPG',
  'CYPG',
  '49.903056',
  '-98.273889',
  '885',
  '-6',
  'A',
  'America/Winnipeg'),
 (103,
  '104',
  'Pitt Meadows',
  'Pitt Meadows',
  'Canada',
  None,
  'CYPK',
  '49.21611',
  '-122.71',
  '11',
  '-8',
  'A',
  'America/Vancouver'),
 (104,
  '105',
  'Pickle Lake',
  'Pickle Lake',
  'Canada',
  'YPL',
  'CYPL',
  '51.446388',
  '-90.214167',
  '1267',
  '-5',
  'A',
  'America/Coral_Harbour'),
 (105,
  '106',
  'Port Menier',
  'Port Menier',
  'Canada',
  'YPN',
  'CYPN',
  '49.836389',
  '-64.288611',
  '167',
  '-5',
  'A',
  'America/Toronto'),
 (106,
  '107',
  'Peterborough',
  'Peterborough',
  'Canada',
  'YPQ',
  'CYPQ',
  '44.23',
  '-78.363333',
  '628',
  '-5',
  'A',
  'America/Toronto'),
 (107,
  '108',
  'Prince Rupert',
  'Prince Pupert',
  'Canada',
  'YPR',
  'CYPR',
  '54.28611',
  '-130.444722',
  '116',
  '-8',
  'A',
  'America/Vancouver'),
 (108,
  '109',
  'Fort Chipewyan',
  'Fort Chipewyan',
  'Canada',
  'YPY',
  'CYPY',
  '58.767223',
  '-111.117222',
  '761',
  '-7',
  'A',
  'America/Edmonton'),
 (109,
  '110',
  'Muskoka',
  'Muskoka',
  'Canada',
  'YQA',
  'CYQA',
  '44.974722',
  '-79.303333',
  '925',
  '-5',
  'A',
  'America/Toronto'),
 (110,
  '111',
  'Quebec Jean Lesage Intl',
  'Quebec',
  'Canada',
  'YQB',
  'CYQB',
  '46.791111',
  '-71.393333',
  '244',
  '-5',
  'A',
  'America/Toronto'),
 (111,
  '112',
  'Red Deer Regional',
  'Red Deer Industrial',
  'Canada',
  'YQF',
  'CYQF',
  '52.182222',
  '-113.894444',
  '2968',
  '-7',
  'A',
  'America/Edmonton'),
 (112,
  '113',
  'Windsor',
  'Windsor',
  'Canada',
  'YQG',
  'CYQG',
  '42.275556',
  '-82.955556',
  '622',
  '-5',
  'A',
  'America/Toronto'),
 (113,
  '114',
  'Watson Lake',
  'Watson Lake',
  'Canada',
  'YQH',
  'CYQH',
  '60.116389',
  '-128.8225',
  '2255',
  '-8',
  'A',
  'America/Vancouver'),
 (114,
  '115',
  'Kenora',
  'Kenora',
  'Canada',
  'YQK',
  'CYQK',
  '49.788334',
  '-94.363056',
  '1332',
  '-6',
  'A',
  'America/Winnipeg'),
 (115,
  '116',
  'Lethbridge',
  'Lethbridge',
  'Canada',
  'YQL',
  'CYQL',
  '49.630278',
  '-112.799722',
  '3047',
  '-7',
  'A',
  'America/Edmonton'),
 (116,
  '117',
  'Greater Moncton Intl',
  'Moncton',
  'Canada',
  'YQM',
  'CYQM',
  '46.112221',
  '-64.678611',
  '232',
  '-4',
  'A',
  'America/Halifax'),
 (117,
  '119',
  'Comox',
  'Comox',
  'Canada',
  'YQQ',
  'CYQQ',
  '49.710833',
  '-124.886667',
  '84',
  '-8',
  'A',
  'America/Vancouver'),
 (118,
  '120',
  'Regina Intl',
  'Regina',
  'Canada',
  'YQR',
  'CYQR',
  '50.431944',
  '-104.665833',
  '1894',
  '-6',
  'N',
  'America/Regina'),
 (119,
  '121',
  'Thunder Bay',
  'Thunder Bay',
  'Canada',
  'YQT',
  'CYQT',
  '48.371944',
  '-89.323889',
  '653',
  '-5',
  'A',
  'America/Toronto'),
 (120,
  '122',
  'Grande Prairie',
  'Grande Prairie',
  'Canada',
  'YQU',
  'CYQU',
  '55.179722',
  '-118.885',
  '2195',
  '-7',
  'A',
  'America/Edmonton'),
 (121,
  '123',
  'Yorkton Muni',
  'Yorkton',
  'Canada',
  'YQV',
  'CYQV',
  '51.264721',
  '-102.461667',
  '1635',
  '-6',
  'N',
  'America/Regina'),
 (122,
  '124',
  'North Battleford',
  'North Battleford',
  'Canada',
  'YQW',
  'CYQW',
  '52.769167',
  '-108.24361',
  '1799',
  '-6',
  'N',
  'America/Regina'),
 (123,
  '125',
  'Gander Intl',
  'Gander',
  'Canada',
  'YQX',
  'CYQX',
  '48.936944',
  '-54.568056',
  '496',
  '-3.5',
  'A',
  'America/St_Johns'),
 (124,
  '126',
  'Sydney',
  'Sydney',
  'Canada',
  'YQY',
  'CYQY',
  '46.161388',
  '-60.047779',
  '203',
  '-4',
  'A',
  'America/Halifax'),
 (125,
  '127',
  'Quesnel',
  'Quesnel',
  'Canada',
  'YQZ',
  'CYQZ',
  '53.026112',
  '-122.510278',
  '1789',
  '-8',
  'A',
  'America/Vancouver'),
 (126,
  '128',
  'Resolute Bay',
  'Resolute',
  'Canada',
  'YRB',
  'CYRB',
  '74.716944',
  '-94.969444',
  '215',
  '-6',
  'A',
  'America/Winnipeg'),
 (127,
  '129',
  'Riviere Du Loup',
  'Riviere Du Loup',
  'Canada',
  'YRI',

Looks like we got some data, but it's not clear what each element represents. We can view the column names in the cursor's `description` attribute.

In [11]:
cursor.description

(('index', None, None, None, None, None, None),
 ('id', None, None, None, None, None, None),
 ('name', None, None, None, None, None, None),
 ('city', None, None, None, None, None, None),
 ('country', None, None, None, None, None, None),
 ('code', None, None, None, None, None, None),
 ('icao', None, None, None, None, None, None),
 ('latitude', None, None, None, None, None, None),
 ('longitude', None, None, None, None, None, None),
 ('altitude', None, None, None, None, None, None),
 ('offset', None, None, None, None, None, None),
 ('dst', None, None, None, None, None, None),
 ('timezone', None, None, None, None, None, None))

## `pd.read_sql()`

We can get the data and the column names into a nice, tidy DataFrame using `pd.read_sql()`

In [12]:
import pandas as pd

airports_df = pd.read_sql(airports_query, con)
airports_df.head()

,index,id,name,city,country,code,icao,latitude,longitude,altitude,offset,dst,timezone
0,0,1,Goroka,Goroka,Papua New Guinea,GKA,AYGA,-6.081689,145.391881,5282,10,U,Pacific/Port_Moresby
1,1,2,Madang,Madang,Papua New Guinea,MAG,AYMD,-5.207083,145.7887,20,10,U,Pacific/Port_Moresby
2,2,3,Mount Hagen,Mount Hagen,Papua New Guinea,HGU,AYMH,-5.826789,144.295861,5388,10,U,Pacific/Port_Moresby
3,3,4,Nadzab,Nadzab,Papua New Guinea,LAE,AYNZ,-6.569828,146.726242,239,10,U,Pacific/Port_Moresby
4,4,5,Port Moresby Jacksons Intl,Port Moresby,Papua New Guinea,POM,AYPY,-9.443383,147.22005,146,10,U,Pacific/Port_Moresby

## Explore the Schema

In SQLite, the schema of our database lives in the `sqlite_master` table. More info [here](https://www.techonthenet.com/sqlite/sys_tables/index.php).

In [13]:
schema_df = pd.read_sql("""
SELECT *
FROM sqlite_master



""", con)

schema_df

,type,name,tbl_name,rootpage,sql
0,table,airports,airports,2,"CREATE TABLE airports (\n[index] INTEGER,\n [..."
1,index,ix_airports_index,airports,3,CREATE INDEX ix_airports_index ON airports ([i...
2,table,airlines,airlines,945,"CREATE TABLE airlines (\n[index] INTEGER,\n [..."
3,index,ix_airlines_index,airlines,946,CREATE INDEX ix_airlines_index ON airlines ([i...
4,table,routes,routes,1393,"CREATE TABLE routes (\n[index] INTEGER,\n [ai..."
5,index,ix_routes_index,routes,1394,CREATE INDEX ix_routes_index ON routes ([index])

It looks like there are three tables in our database: airports, airlines, and routes. Each table also has an **index**, which is used to optimize queries for large databases. 

The column names and datatypes for each table are defined in the schema in the `sql` column.

In [14]:
# Airports table info

print(schema_df['sql'].iloc[0])

CREATE TABLE airports (
[index] INTEGER,
  [id] TEXT,
  [name] TEXT,
  [city] TEXT,
  [country] TEXT,
  [code] TEXT,
  [icao] TEXT,
  [latitude] TEXT,
  [longitude] TEXT,
  [altitude] TEXT,
  [offset] TEXT,
  [dst] TEXT,
  [timezone] TEXT
)

## Exercise

Get the columns and datatypes for the airlines table. You can do this with either `pd.read_sql()` or the schema table.

<details>
    <summary><b><u>Click Here for Answer Code</u></b></summary>

```python 
pd.read_sql("""

SELECT *       
FROM airlines

""", con).info()
```

OR

```python 
print(schema_df['sql'].iloc[2])
```
</details>

In [17]:
print(schema_df['sql'].iloc[2])

CREATE TABLE airlines (
[index] INTEGER,
  [id] TEXT,
  [name] TEXT,
  [alias] TEXT,
  [iata] TEXT,
  [icao] TEXT,
  [callsign] TEXT,
  [country] TEXT,
  [active] TEXT
)

In [20]:
#or you can do it this way....

In [19]:
pd.read_sql(
"""
    SELECT *
    FROM airlines;
""", con
).info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6048 entries, 0 to 6047
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   index     6048 non-null   int64
 1   id        6048 non-null   object
 2   name      6048 non-null   object
 3   alias     5615 non-null   object
 4   iata      1461 non-null   object
 5   icao      5961 non-null   object
 6   callsign  5305 non-null   object
 7   country   6033 non-null   object
 8   active    6048 non-null   object
dtypes: int64(1), object(8)
memory usage: 425.4+ KB

# Writing SQL Queries

In this section we will build SQL queries using the SELECT statement, showing off a bunch of different clauses and options available.

## SELECT Statement

SELECT statements can have multiple **clauses**, which must be included in a specific order (more info [here](https://sqlite.org/lang_select.html)). Only SELECT and FROM are required.

Let's explore the following clauses and structure:

```sql
SELECT columns
FROM table
WHERE condition
ORDER BY columns
LIMIT number
```

## SELECT: Picking Columns

Add the names of the columns that you want after the word `SELECT`, or use `*` to get all columns.

In [18]:
#Fill in code after the SELECT statement below

pd.read_sql("""

SELECT *
FROM airports

""", con)

,index,id,name,city,country,code,icao,latitude,longitude,altitude,offset,dst,timezone
0,0,1,Goroka,Goroka,Papua New Guinea,GKA,AYGA,-6.081689,145.391881,5282,10,U,Pacific/Port_Moresby
1,1,2,Madang,Madang,Papua New Guinea,MAG,AYMD,-5.207083,145.7887,20,10,U,Pacific/Port_Moresby
2,2,3,Mount Hagen,Mount Hagen,Papua New Guinea,HGU,AYMH,-5.826789,144.295861,5388,10,U,Pacific/Port_Moresby
3,3,4,Nadzab,Nadzab,Papua New Guinea,LAE,AYNZ,-6.569828,146.726242,239,10,U,Pacific/Port_Moresby
4,4,5,Port Moresby Jacksons Intl,Port Moresby,Papua New Guinea,POM,AYPY,-9.443383,147.22005,146,10,U,Pacific/Port_Moresby
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8102,8102,9537,Mansons Landing Water Aerodrome,Mansons Landing,Canada,YMU,\N,50.066667,-124.983333,0,-8,A,America/Vancouver
8103,8103,9538,Port McNeill Airport,Port McNeill,Canada,YMP,\N,50.575556,-127.028611,225,-8,A,America/Vancouver
8104,8104,9539,Sullivan Bay Water Aerodrome,Sullivan Bay,Canada,YTG,\N,50.883333,-126.833333,0,-8,A,America/Vancouver
8105,8105,9540,Deer Harbor Seaplane,Deer Harbor,United States,DHB,\N,48.618397,-123.00596,0,-8,A,America/Los_Angeles
8106,8106,9541,San Diego Old Town Transit Center,San Diego,United States,OLT,\N,32.7552,-117.1995,0,-8,A,America/Los_Angeles

### `DISTINCT`

Use `DISTINCT` to drop duplicates.

In [23]:
#Fill in code after the SELECT statement below
pd.read_sql("""

SELECT DISTINCT country
FROM airports

""", con)

                           country
0                 Papua New Guinea
1                        Greenland
2                          Iceland
3                           Canada
4                          Algeria
..                             ...
235  South Georgia and the Islands
236                        Myanmar
237                       Svalbard
238                    North Korea
239                    Wake Island

[240 rows x 1 columns]

### `AS`

Use `AS` to rename columns.

In [28]:
#creating an alias for both columns and/or tables

In [27]:
#Fill in code after the SELECT statement below
pd.read_sql("""

SELECT city AS "airport_city", country AS "airport_country"
FROM airports AS a

""", con)

         airport_city   airport_country
0              Goroka  Papua New Guinea
1              Madang  Papua New Guinea
2         Mount Hagen  Papua New Guinea
3              Nadzab  Papua New Guinea
4        Port Moresby  Papua New Guinea
...               ...               ...
8102  Mansons Landing            Canada
8103     Port McNeill            Canada
8104     Sullivan Bay            Canada
8105      Deer Harbor     United States
8106        San Diego     United States

[8107 rows x 2 columns]

### Functions

There are dozens of functions that you can use in SELECT statements to modify results - you can see some examples [here](https://sqlite.org/lang_corefunc.html).

In [32]:
#Fill in code after the SELECT statement below
pd.read_sql("""

SELECT UPPER(name) AS "AIRPORT NAMES IN CAPS", LOWER(name) AS "airport names lower"
       
FROM airports

""", con)

                  AIRPORT NAMES IN CAPS                airport names lower
0                                GOROKA                             goroka
1                                MADANG                             madang
2                           MOUNT HAGEN                        mount hagen
3                                NADZAB                             nadzab
4            PORT MORESBY JACKSONS INTL         port moresby jacksons intl
...                                 ...                                ...
8102    MANSONS LANDING WATER AERODROME    mansons landing water aerodrome
8103               PORT MCNEILL AIRPORT               port mcneill airport
8104       SULLIVAN BAY WATER AERODROME       sullivan bay water aerodrome
8105               DEER HARBOR SEAPLANE               deer harbor seaplane
8106  SAN DIEGO OLD TOWN TRANSIT CENTER  san diego old town transit center

[8107 rows x 2 columns]

#### Aggregation

Some functions will aggregate your data and return a table with one row.

In [38]:
#Fill in code after the SELECT statement below
pd.read_sql("""

SELECT COUNT()
FROM airports

""", con)

   COUNT()
0     8107

#### Datatype Compatibility

Make sure that your column is the right datatype for the function to avoid unexpected results.

In [46]:
pd.read_sql("""

SELECT name AS "Airport Name", 
       MAX(CAST(altitude as INT)) AS "Altitude (ft)"
       
FROM airports

""", con)

      Airport Name  Altitude (ft)
0  Yading Daocheng          14472

#### `CAST()`

You could fix this using the `CAST()` function.

In [44]:
#Fill in the CAST() function in the appropriate location below
pd.read_sql("""

SELECT name AS "Airport Name", 
       MAX(CAST(altitude as INT)) AS "Altitude (ft)"
       
FROM airports

""", con)

      Airport Name  Altitude (ft)
0  Yading Daocheng          14472

### Exercise

Which country has the northern-most airport? 

> _Hint: Look for the highest latitude_

<details>
    <summary><b><u>Click Here for Answer Code</u></b></summary>

```python 
pd.read_sql("""

SELECT country AS "Country", 
       MAX(CAST(latitude as int)) AS "Latitude"

FROM airports

""", con)
```
</details>

In [50]:

pd.read_sql("""

SELECT country,
       MAX(CAST(latitude as INT)) AS "Latitude"
       
FROM airports

""", con)

  country  Latitude
0  Canada        82

## FROM: Picking Tables

The `FROM` clause specifies the tables you get data from. You can use aliases here with `AS` - this will be useful for more complex queries involving multiple tables.

In [51]:
#Fill in code for the FROM clause below
pd.read_sql("""

SELECT ap.name AS "Airport Name", 
       MAX(CAST(ap.altitude AS int)) AS "Altitude (ft)"
       FROM airports AS ap


""", con)

      Airport Name  Altitude (ft)
0  Yading Daocheng          14472

## WHERE: Picking Rows

The `WHERE` clause filters results from your query. This uses conditional logic and operators similar to Python's - you can find more [here](https://sqlite.org/lang_expr.html).

In [52]:
#Fill in the WHERE clause below
pd.read_sql("""

SELECT name AS "Airport Name", 
       CAST(latitude AS int) AS "Airport Latitude",
       CAST(altitude AS int) AS "Altitude (ft)"
       
FROM airports

WHERE "Altitude (ft)" > 10000
    AND "Airport Latitude" BETWEEN 20 AND 50


""", con)

              Airport Name  Airport Latitude  Altitude (ft)
0                      Leh                34          10682
1        Hongyuan Airfield                32          11500
2            Lhasa-Gonggar                29          13136
3                   Manang                28          11000
4     Jiuzhaigou Huanglong                32          11311
5     Qamdo Bangda Airport                30          14219
6                    Maiwa                33          11500
7               Syangboche                27          12309
8             Yushu Batang                32          13000
9                    Gunsa                32          13780
10  Shigatse Peace Airport                29          12408
11        Kangding Airport                30          14042
12         Yading Daocheng                29          14472
13                  Gannan                34          10466

### `IS`

The `IS` operator is useful when working with `NULL` values - other operators will not work as expected.

In [53]:
#Fill in code in the WHERE clause below
pd.read_sql("""

SELECT name AS "Airport Name",
       code AS "Airport Code"
       
FROM airports

WHERE "Airport Code" IS NULL
""", con)

         Airport Name Airport Code
0         Forestville         None
1        Pitt Meadows         None
2               Blida         None
3           Bou Saada         None
4             Reggane         None
...               ...          ...
2222              Bus         None
2223              Bus         None
2224              Bus         None
2225     Main Station         None
2226  Algerciras Port         None

[2227 rows x 2 columns]

In [54]:
#Fill in code in the WHERE clause below
pd.read_sql("""

SELECT name AS "Airport Name",
       code AS "Airport Code"
       
FROM airports

WHERE "Airport Code" IS NOT NULL
""", con)

                           Airport Name Airport Code
0                                Goroka          GKA
1                                Madang          MAG
2                           Mount Hagen          HGU
3                                Nadzab          LAE
4            Port Moresby Jacksons Intl          POM
...                                 ...          ...
5875    Mansons Landing Water Aerodrome          YMU
5876               Port McNeill Airport          YMP
5877       Sullivan Bay Water Aerodrome          YTG
5878               Deer Harbor Seaplane          DHB
5879  San Diego Old Town Transit Center          OLT

[5880 rows x 2 columns]

## ORDER BY: Sorting Results

Use `ORDER BY` to identify the column(s) you want to sort on. Specify `ASC` for ascending order, `DESC` for descending order.

In [57]:
#Fill in the ORDER BY clause below
pd.read_sql("""

SELECT name AS "Airport Name", 
       CAST(latitude AS int) AS "Airport Latitude",
       CAST(altitude AS int) AS "Altitude (ft)"
       
FROM airports

WHERE "Altitude (ft)" >= 10000

ORDER BY "Airport Latitude" DESC,
        "Altitude (ft)" ASC
         
""", con)

                              Airport Name  Airport Latitude  Altitude (ft)
0                              Summit Camp                72          10552
1                              Summit Camp                72          11000
2                                Irkutsk-2                52          13411
3                                   Gannan                34          10466
4                                      Leh                34          10682
5                                    Maiwa                33          11500
6                     Jiuzhaigou Huanglong                32          11311
7                        Hongyuan Airfield                32          11500
8                             Yushu Batang                32          13000
9                                    Gunsa                32          13780
10                        Kangding Airport                30          14042
11                    Qamdo Bangda Airport                30          14219
12                  Shigatse Peace Airport                29          12408
13                           Lhasa-Gonggar                29          13136
14                         Yading Daocheng                29          14472
15                                  Manang                28          11000
16                              Syangboche                27          12309
17                         Francisco Carle               -11          11034
18  Teniente Alejandro Velasco Astete Intl               -13          10860
19                             Andahuaylas               -13          11300
20                     Poroy Train Station               -13          11710
21                                 Juliaca               -15          12552
22                      Copacabana Airport               -16          12591
23                            El Alto Intl               -16          13325
24                            Juan Mendoza               -17          12146
25                   Capitan Nicolas Rojas               -19          12913
26                           Uyuni Airport               -20          11990
27                          Salar de Uyuni               -20          12000
28                            Isla Pescado               -20          12020
29                               La Quiaca               -22          11414

## LIMIT: Number of Results

Specify the maximum number of results you want

In [58]:
#Fill in a LIMIT clause below
pd.read_sql("""

SELECT name AS "Airport Name", 
       CAST(latitude AS int) AS "Airport Latitude",
       CAST(altitude AS int) AS "Altitude (ft)"
       
FROM airports

WHERE "Altitude (ft)" >= 10000

ORDER BY "Airport Latitude" DESC,
         "Altitude (ft)" DESC 
         
LIMIT 10

""", con)

           Airport Name  Airport Latitude  Altitude (ft)
0           Summit Camp                72          11000
1           Summit Camp                72          10552
2             Irkutsk-2                52          13411
3                   Leh                34          10682
4                Gannan                34          10466
5                 Maiwa                33          11500
6                 Gunsa                32          13780
7          Yushu Batang                32          13000
8     Hongyuan Airfield                32          11500
9  Jiuzhaigou Huanglong                32          11311

# Exercises

## Country List

Create a list of countries with airports and order them alphabetically A-Z.

> _Hint: You will need to remove duplicates._

<details>
    <summary><b><u>Click Here for Answer Code</u></b></summary>

```python 
pd.read_sql("""

SELECT DISTINCT country
FROM airports
ORDER BY country ASC

""", con)
```
</details>

In [67]:
# Your work here
pd.read_sql("""

SELECT DISTINCT country AS "Country Name"
FROM airports
ORDER BY country

""", con)

       Country Name
0       Afghanistan
1           Albania
2           Algeria
3    American Samoa
4            Angola
..              ...
235       West Bank
236  Western Sahara
237           Yemen
238          Zambia
239        Zimbabwe

[240 rows x 1 columns]

## Southern Airports

Get the name, country and latitude of the 10 southern-most airports. 

> _Hint: Look for the smallest latitude._

<details>
    <summary><b><u>Click Here for Answer Code</u></b></summary>

```python 
pd.read_sql("""

SELECT name, country, CAST(latitude AS int) AS "Airport Latitude"
FROM airports
ORDER BY "Airport Latitude" ASC
LIMIT 10

""", con)
``` 
</details>

In [68]:
# Your work here
pd.read_sql("""

SELECT name, country, latitude
FROM airports
ORDER BY CAST(latitude AS int) ASC
LIMIT 10

""", con)

                            name         country     latitude
0             South Pole Station      Antarctica   -89.999997
1                Mcmurdo Station      Antarctica   -77.867358
2    Ice Runway-McMurdo Sstation      Antarctica  -77.8477778
3  McMurdo Station Pegasus Field      Antarctica   -77.963333
4                 South Shetland      Antarctica          -68
5       Rothera Research Station  United Kingdom       -67.34
6                 Wilkins Runway      Antarctica   -66.689444
7                     Antarctica      Antarctica          -66
8                     Antarctica      Antarctica          -66
9                  Base Marambio      Antarctica   -64.238335

## Active UK Airlines

Create a list of active airlines in the United Kingdom from the airlines table. 

> _Hint: You will need to explore the airlines table to figure out how to do this._

<details>
    <summary><b><u>Click Here for Answer Code</u></b></summary>

```python 
pd.read_sql("""

SELECT name
FROM airlines
WHERE active='Y'
AND country='United Kingdom'

""", con)
```
</details>

In [ ]:
# Your work here

## Explore Routes

Get the column names from the routes table and inspect some raw data. Which columns might be keys that connect this table to the other two tables?

<details>
    <summary><b><u>Click Here for Answer Code</u></b></summary>

```python 
pd.read_sql("""

SELECT *
FROM routes
LIMIT 5

""", con)
```   
> The airline_id is a foreign key to the airlines table, the source_id and dest_id columns are foreign keys to the airports table
    
</details>

In [ ]:
# Your work here

# Level Up: `CASE`

Use `CASE` to create new columns using conditional logic.

In [69]:
pd.read_sql("""

SELECT name AS "Airport Name", 
       CAST(altitude AS int) AS "Altitude (ft)",
       CASE 
            WHEN CAST(altitude AS int) > 1000 THEN "High"
            WHEN CAST(altitude AS int) < 100 THEN "Low"
            ELSE "Moderate"
       END AS "Altitude Category"
       
FROM airports
         
LIMIT 20

""", con)

                      Airport Name  Altitude (ft) Altitude Category
0                           Goroka           5282              High
1                           Madang             20               Low
2                      Mount Hagen           5388              High
3                           Nadzab            239          Moderate
4       Port Moresby Jacksons Intl            146          Moderate
5                       Wewak Intl             19               Low
6                       Narsarsuaq            112          Moderate
7                             Nuuk            283          Moderate
8                Sondre Stromfjord            165          Moderate
9                   Thule Air Base            251          Moderate
10                        Akureyri              6               Low
11                     Egilsstadir             76               Low
12                    Hornafjordur             24               Low
13                         Husavik             48               Low
14                      Isafjordur              8               Low
15  Keflavik International Airport            171          Moderate
16                  Patreksfjordur             11               Low
17                       Reykjavik             48               Low
18                    Siglufjordur             10               Low
19                  Vestmannaeyjar            326          Moderate

# Level Up: SQL Joins

SQL joins can be used to both **add** data to a table and **remove** data from a table.

![venn](images/venn.png)

How are these different joins possible?

Notice that I choose a column from each table "on" which to effect the join. This is the means by which I pair up the records from one table with the records of another.

Look back up at the sample diagram under "What is a Relational Database?". We might use the "student_id" column to match up names in the names table with grades in the grades table. But what if there are values in one table's version of "student_id" that don't appear in the other table's version? In that case we need to let the software know whether or not we want to have *all* of the records, regardless of whether they have corresponding entries in all the tables we are joining. This makes for the variety depicted above.

- If I select records from "A INNER JOIN B", then a record will be displayed *only if it exists in both tables*.

- If I select records from "A LEFT JOIN B", then *all relevant records from A will be displayed*, regardless of whether they have representation in B. Records from B with no representation in A will *not* be displayed.

In [ ]:
pd.read_sql("""

    SELECT p.name, l.name, p.country
    FROM airports p
    LEFT JOIN airlines l
    ON p.country=l.country
    ORDER BY l.name
    LIMIT 5
    
""", con)

In [ ]:
pd.read_sql("""
    
    SELECT p.name, l.name, p.country
    FROM airports p
    INNER JOIN airlines l
    ON p.country=l.country
    ORDER BY l.name
    LIMIT 5
    
""", con)